### ISSUE TITLE
what is duckdb-go-api?

### ISSUE THREAD

**Issue by dawsondong** [taniabogatsch/goofy-duck#1]
Hello,

Could you please explain a little on the usage of code about duckdb-go-api? What is it? How can I get it? Would it be possible to use marcboeker/go-duckdb instead?

Thanks!

**Comment by taniabogatsch** [comment]
Hi @dawsondong!

At this stage, this repo (goofy-duck) is a proof of concept for writing Go duckdb extensions using the C API instead of the C++ interface. Without the need to write any C code or cgo. I am not entirely there yet, as seen by the C code here: https://github.com/taniabogatsch/goofy-duck/blob/d0737d3097e8baa9d982dc97c8dd0d2047337606/my_addition.go#L4

duckdb-go-api is a lightweight Go wrapper for duckdb's C API functions. In its current state, it is far from any official wrapper, and I mainly use it for the goofy-duck proof of concept.

It differs from go-duckdb because it does not implement Go's SQL driver interface. It only wraps the C API functions in Go functions. Conceptionally, this means that (at some more distant point in time) go-duckdb could use these wrapper functions to replace most of its C code. However, they are not a substitute for each other.

**Comment by dawsondong** [comment]
Thanks @taniabogatsch ,

I see now on your saying. Finally, I made all work! Good start!
